# Generated by Django 5.2.7 on 2025-10-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False, help_text='Usuário tem acesso de administrador?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='manager',
            field=models.BooleanField(default=False, help_text='Usuário é gerente?'),
        ),
    ]
