# Generated by Django 5.2.7 on 2025-10-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_admin_usuario_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pode_postar',
            field=models.BooleanField(default=True, help_text='Usuário pode criar postagens?'),
        ),
    ]
